- actions/demultiplex.yaml
- actions/get_flowcell_from_runfolder_name.yaml
- actions/lib/get_flowcell_from_runfolder_name.py
- actions/workflows/demultiplex.yaml
- actions/workflows/ngi_uu_workflow.yaml
- actions/workflows/sisyphus_qc.yaml
- actions/workflows/sisyphus_quickreport.yaml
Also some some small refactoring of where the runfolder name is picked up.
> Introduce way to get flowcell name

- actions/demultiplex.yaml
- actions/get_pack_config.yaml
- actions/lib/get_flowcell_from_runfolder_name.py
- actions/lib/get_pack_config.py
- actions/lib/parse_arguments_to_json.py
- actions/lib/poll_status.py
- actions/parse_bcl2fastq_args.yaml
- actions/workflows/demultiplex.yaml
- config.yaml
A bunch of changes to make bcl2fastq work with Hermes. Also caught a small bug in the poll_status script.
> Make demux workflow work with Hermes

- actions/ngi_uu_workflow.yaml
- actions/rsync.yaml
- actions/rsync_file_list.yaml
- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
Right now we are not getting passing the config/qc files for Sisyphus from Hermes. But I know @johanherman has been working on that so we should be able to add that fairly easily. Next thing is to check all checksums after the transfer and then kick-off aeacus-report.
> Everything up to sync to remote host working

- actions/ngi_uu_workflow.yaml
- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
So we can overwrite this file from sysadm orchestration for production deployment
> Set more static values in config.yaml instead,

- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
Changed to order of things a bit, and add setting the runfolder state to the flow. Now the whole workflow is implemented... :satisfied:
> Mark runfolder state

- README.md
- actions/create_sis_style_checksums.yaml
- actions/parse_siswrap_args.yaml
- actions/workflows/ngi_uu_workflow.yaml
- sensors/runfolder_sensor.yaml
Also made some small improvements to the README, adding more examples to make it easier to get up and running.
> Fixing some minor problems

- config.yaml
- scripts/cancel_all
- scripts/querylogs
- sensors/runfolder_sensor.py
- sensors/runfolder_sensor.yaml
- Configurable runfoldersvc URLs
- Timestamp when sensing a new runfolder
- Sensor runs every 30 seconds
> Cleanup of runfolder sensor

- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
We need to do this - otherwise st2 will try to login as the system user which will in general not work.
> Explicitly set user on remote cmds

- actions/create_sis_style_checksums.yaml
- actions/lib/create_sis_style_checksums.sh
- actions/parse_siswrap_args.yaml
- actions/rsync.yaml
- actions/workflows/ngi_uu_workflow.yaml
Fixed changes required to get everything working in our staging environment. This might have broken some things in the Vagrant test environment - which we will have to fix later. But for now I think it will be ok.
> Changes from staging

- actions/create_sis_style_checksums.yaml
- actions/lib/create_sis_style_checksums.sh
- actions/lib/poll_status.py
- actions/sync_workflow.yaml
- actions/workflows/ngi_uu_workflow.yaml
- actions/workflows/sync_workflow.yaml
- config.yaml
- scripts/get_runfolder_log.py
> Merge devel to master

- actions/create_sis_style_checksums.yaml
- actions/lib/poll_status.py
- actions/poll_status.yaml
- actions/rsync.yaml
- actions/workflows/ngi_uu_workflow.yaml
These changes smooth our any incompatibilities with st2 1.4 in our workflow.
This is ready for review, but don't merge until I say so, since we it's still being integration tested.
> WIP: Compatibility with st2 1.4

- actions/charon_project_status.yaml
- actions/lib/charon_project_status.py
- config.yaml
- requirements.txt
- rules/charon_project_status.yaml
This converts the script create by @b97pla to get a project status update from charon to a st2 action and adds a rule to run that action every Monday morning.
> Charon project status

- README.md
- actions/poll_status.py
- actions/poll_status.yaml
- actions/workflows/ngi_uu_workflow.yaml
- tests/test_poll_status.py
Added index checking to the workflow (related PR at siswrap here: https://github.com/arteria-project/arteria-siswrap/pull/16).
In addition to this I fixed a error in the README, removed a unused config value, and refactored the `poll_status` script to use the st2 method of logging and returning for exit codes.
> Add index checking to workflow

- actions/lib/parse_arguments_to_json.py
- actions/poll_status.py
- actions/poll_status.yaml
- actions/workflows/ngi_uu_workflow.yaml
- tests/test_poll_status.py
Combines starting a run on an arteria service and polling it til it finishes into a single action. This should make it easier for us to restart workflow from where they failed.
> Combine poll and post

- actions/arteria_delivery_service.py
- actions/delivery_service_deliver.yaml
- actions/delivery_service_delivery_status.yaml
- actions/delivery_service_stage_project.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/lib/charon_project_status.py
- actions/lib/slack.py
- actions/post_to_slack.yaml
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
- config.yaml
This are the results of the changes need to bring things to an up and running state on irma. In addition to this it adds slack notification to the workflow.
> Changes from integration testing with irma

- actions/download_samplesheet_clarity.py
- actions/download_samplesheet_clarity.yaml
Added action for download of sample sheets from the clarity lims.
> Ssheet from lims

- actions/workflows/delivery_runfolder_workflow.yaml
Apikey added to projects_on_runfolder
Changed tabs to spaces
> Add apikey

- scripts/trace_runfolder.py
Changed script to list workflows for same runfolder in cronological order.
> Restarted workflows will be listed in cronological order

- actions/check_ngi_ready_in_supr.yaml
- actions/create_delivery_project_in_supr.yaml
- actions/delivery_service_deliver.yaml
- actions/delivery_service_delivery_status.yaml
- actions/delivery_service_stage_project.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/get_pi_id_for_email_from_supr.yaml
This hides the tokens in the executions, but it will still show up in some of the logs.
> Hide tokens in executions

- actions/read_projects_email_file.py
- actions/read_projects_email_file.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
when restrict_to_projects is specified
> Only use given projects when searching for e-mails in pi e-mail file

- actions/charon_set_delivery_status.yaml
- actions/delivery_project_workflow.yaml
- actions/lib/charon.py
- actions/workflows/delivery_project_workflow.yaml
I created a new Charon class, but I have not moved the old code which interacts with Charon to it, since I though perhaps @b97pla who wrote it originally would want to have a say in how that was done.
> Set delivery status in charon for BP samples

- README.md
A nice little asciinema demo added to the README.
> Add ascinema demo to README

- README.md
- docker-compose.yml
This pull request:
- Cleans up the README
- Pins Stackstorm to the latest version
> Develop 444 update arteria packs for publication
