arteria-project/arteria-packs

- actions/parse_siswrap_args.yaml
- actions/workflows/ngi_uu_workflow.yaml
Construct the Siswrap body with Sisyphus and QC config. Fetch the files from Hermes.
> Fetch conf from Hermes and inject into Siswrap 

- actions/create_sis_style_checksums.yaml
- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
Now we create and check the MD5 checksums. It's written into the `<runfolder>/MD5/checksums.md5` directory, and the reason for that is that I believe that Sisyphus assumes that checksums are stored there.
> Everything up to sisyphus scripts start works

- README.md
- actions/workflows/ngi_uu_workflow.yaml
- scripts/trace_runfolder.py
Adding a `trace_runfolder.py` script, which can be used to trace all executions for a tag. Basically a utility wrapper for a few of the StackStorm API, but it should make things a lot smoother for the operator.
> Traciblity

- actions/workflows/ngi_uu_workflow.yaml
Since if we have many simultaneously running processes - we might need to wait for a long time to move beyond this step.
> Set 24 h timeout on polling demux process

- actions/create_sis_style_checksums.yaml
- actions/poll_status.yaml
- actions/rsync.yaml
- actions/workflows/sync_workflow.yaml
Since quick-reports are not that quick, and resyncing TB is also slow business, we need longer timeouts.
> Change from 10 h to 24 h timeouts

- sensors/runfolder_sensor.yaml
Right now we see problematic behaviour since the same runfolder gets
started multiple times when many things are running simultaneously.
> Increase sensor poll time to 5 min

- actions/lib/poll_status.py
- actions/rsync.yaml
- actions/workflows/ngi_uu_workflow.yaml
- actions/workflows/sync_workflow.yaml
- config.yaml
- scripts/create_dot_graph.py
- sensors/runfolder_client.py
This pull request ensures that the workflow:
- can rsync to irma
- state is harmonized with version v1.1.0 of the `arteria-runfolder` service
- that picking up runfolders from the `arteria-runfolder` service is done through the new `pickup` endpoint.
It also: 
- makes the `poll_status.py` script retry failed connections, hopefully making it a bit more robust to minor network issues.
- Adds `create_dot_graph.py` - a small script that can create a graphical representation of the workflow in dot format. Useful for documentation purposes.
> Sync to irma and misc

- actions/workflows/fill_projman.yaml
- config.yaml
For the fill-projman workflow to work with Stackstorm v2 we need to pass the `private_key` argument to our `core.remote` and `remote-shell-script` actions (even though I thought it wasn't necessary for the latter according to the docs...). 
This branch has now been tested to work OK in staging at least.
> Make fill-projman workflow conform to Stackstorm v2

- actions/gather_ngi_pipeline_reports.yaml
- actions/workflows/gather_ngi_pipeline_reports.yaml
- config.yaml
- rules/gather_ngi_pipeline_reports.yaml
This enables downloading of our ngi pipeline reports from a specific directory on irma. It introduces two new configuration values, namely: `summary_ngi_pipeline_reports_destination` and `irma_reports_remote_path`.
> Get ngi pipeline reports

- actions/workflows/ngi_uu_workflow.yaml
Obviously we should also archive runfolders that have been processed on Irma, and not only those that have been processed on Milou. Missed to add the call to both execution paths in previous PR.
> Bug fix: Archive runs destignated for Irma as well

- actions/lib/swap_read_nr_in_conversionstats.sh
- actions/ngi_uu_workflow.yaml
- actions/workflows/ngi_uu_workflow.yaml
Due to a bug in bcl2fastq sometimes the read number in Unaligned/Stats/ConversionStats.xml gets set to 65 instead of 1, which will cause Sisyphus to fail. When this happens the bioinformaticians want to be able to manually override the workflow and force the read number to be swapped to a more appropriate value (usually 1). 
Have tested the logic on staging server with a smaller subset of the NGI UU workflow.
> Bug fix: Swap read number in ConversionStats.xml

- actions/workflows/archive_workflow.yaml
The find subprocess didn't follow symlinks correctly before. This made us miss calculating checksums for data under `Unaligned`, which usually are a symlink (on some of the test data sets `Unaligned` was setup as a standard folder).
> Bug fix: calculate checksums for all files before archiving 

- actions/lib/prepare_archive_package.sh
- actions/workflows/archive_workflow.yaml
We've updated our local arteria-packs config for what files to exclude from the PDC archive tarball. This PR just updates the example in the script for consistency's sake.
> Update example with what files to exclude

- actions/workflows/archive_workflow.yaml
Due to indentation errors on the checksum action the default timeout 60 seconds was used instead. Due to mainly testing with MiSeq runfolders this default value was never hit during initial development, but of course when starting to calculate checksums for HiSeqX runfolders a longer period is required. This has been hot-fixed on arteria-master so that Matilda can run her archiving workflows manually.
> Timeout param was not set correctly

- actions/arteria_delivery_service.py
- actions/create_delivery_project_in_supr.yaml
- actions/delivery_runfolder_workflow.yaml
- actions/delivery_service_deliver.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/get_pi_id_for_email_from_supr.yaml
- actions/read_projects_email_file.py
- actions/read_projects_email_file.yaml
- actions/supr.py
- actions/workflows/delivery_runfolder_workflow.yaml
- config.yaml
This implements the delivery workflow for a runfolder for the following stages so far:
It should be ready for some initial code review at this point, but it's not yet ready to be merged.
In addition to this we will need to implement running deliveries on arbitrary folder structures - so that e.g. WGS projects can also be delivered.
> WIP: Delivery workflow

- actions/workflows/fill_projman.yaml
Instead of spamming mm-xlas002 with tons of ssh logins we will now limit it to 5 concurrent logins at a time. Hopefully this might also help with the mysterious problems we've had with st2api from time to time.
> Limit no of concurrent logins to mm-xlas002 

- actions/arteria_delivery_service.py
- actions/delivery_project_workflow.yaml
- actions/delivery_service_stage_project.yaml
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
Added a delivery workflow which can deliver an arbitrary project (defined as a directory with the same name as the project placed in the location monitored by the arteria delivery service).
There is a fair amount of code duplication between this and the runfolder delivery workflow, but right now I'm not sure that refactoring this into subworkflows is worth the trouble. Especially since I guess we are dropping doing deliveries straight from runfolders in the future.
> Deliver arbitrary project

- actions/archive_workflow.yaml
- actions/compress_archive_package.yaml
- actions/create_archive_dir.yaml
- actions/lib/compress_archive_package.sh
- actions/lib/create_archive_dir.py
- actions/lib/prepare_archive_package.sh
- actions/ngi_uu_workflow.yaml
- actions/workflows/archive_workflow.yaml
- actions/workflows/ngi_uu_workflow.yaml
- config.yaml
@MatildaAslin , @slohse: Feel free to give input to the below if you have time/interest, so you both can start having a bit better insight into how the workflows are built up. 
Instead of filtering on TSM level which files we should include and exclude in the upload to PDC we will now instead create a linked tree structure called `<runfolder>_archive` with the `create_archive_dir.py` script. This also gives us less output from the TSM client 
The previous script that compressed the archive is modified somewhat to work properly with the links. 
When launching the NGI UU workflow one can now set a param `skip_archiving=true` to skip the archive subworkflow (practical e.g. when testing other parts of the workflow in staging). An other option is also added if the operator wants to re-run an …
> Archive a linked tree structure instead of filtering on TSM level 

- actions/poll_status.py
- actions/workflows/ngi_uu_workflow.yaml
Changes `poll_status.py` so that the microservice's response payload is written out (will appear in Stackstorms stderr field for the action). That way we e.g. can see what version of Sisyphus that was used for the arteria-siswrap actions. 
Also adds a new action to the NGI UU workflow that parses the stderr from the bcl2fastq action, looking for the payload in the first line of the stderr string. It will then save the bcl2fastq version used into the file `<runfolder>/bcl2fastq_version`. 
Tested on a MiSeq runfolder in staging.
> Log version of Arteria service and bcl2fastq used

- actions/arteria_delivery_service.py
- actions/create_delivery_project_in_supr.yaml
- actions/supr.py
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
This code ensures that we pick up the size of a delivery and pass it along when creating a delivery project. The smallest allocation it will make in supr is for 1 GB, otherwise it will be the size of the delivery in GB rounding up.
> Pass size of delivery along when creating delivery project

- actions/arteria_delivery_service.py
- actions/delivery_project_workflow.yaml
- actions/delivery_runfolder_workflow.yaml
- actions/delivery_service_delivery_status.yaml
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
This introduces a option to the delivery workflows to skip calling mover when running a delivery. This is so that we can do light integration testing without running a real delivery.
It also separates the checking of delivery status from the starting a delivery, so that workflows can be restarted from the status checking stage if we experience intermittent failures.
> Changes preping to use the real mover

- actions/arteria_delivery_service.py
- actions/check_ngi_ready_in_supr.yaml
- actions/delivery_project_workflow.yaml
- actions/delivery_runfolder_workflow.yaml
- actions/delivery_service_deliver.yaml
- actions/delivery_service_delivery_status.yaml
- actions/delivery_service_stage_project.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/supr.py
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
Added a step to the workflow that will check that the `ngi_ready` flag is set in supr. Also made polling wait times configurable, so that we won't spam mover info, etc, every 5 seconds. The default is not 5 minutes, but it is configurable, so that it can be lowered during testing.
> Check ngi ready and configurable polling wait times

- actions/workflows/fill_projman.yaml
A lot of `rsync_from_irma` tasks in the `fill_projman` workflow fail because they do not finish in 60 s. Since Summary folders be up to ~ 600 Mb, I think the sync should be given more time to complete.
> Added 5 h timeout for rsync from Irma to Seq-Summaries

- actions/check_irma_certs.yaml
- actions/workflows/check_irma_certs.yaml
- config.yaml
- rules/check_irma_certs.yaml
Simple and dirty check of Irma SSH certs on Arteria associated hosts (compute and seq summary hosts). Will warn if they are about to expire within 14 days by sending a message to a Slack channel each morning. 
"mm-xart003" refers to a manual dummy entry in /etc/hosts so I could test checking vs many hosts in one action.
> Warn when Irma SSH certs are about to expire

- actions/lib/swap_read_nr_in_conversionstats.sh
- actions/ngi_uu_workflow.yaml
- actions/workflows/ngi_uu_workflow.yaml
Remove workaround as it is fixed in latest version of bcl2fastq that we are now using.
> Rollback ConversionStats workaround

- actions/create_delivery_project_in_supr.yaml
- actions/get_pi_id_for_email_from_supr.yaml
- actions/read_projects_email_file.py
- actions/supr.py
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
Information about sensitive projects will now be sent to SUPR. If a project is sensitive or not is given by the delivery-operator in a text-file used as input in the delivery-workflow.
> Update sensitive project info

- README.md
- actions/arteria_delivery_service.py
- actions/delivery_runfolder_workflow.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/supr.py
- actions/workflows/delivery_runfolder_workflow.yaml
- utils/prepare_test_env.sh
When running the delivery workflow for a runfolder the parameter restrict_to_projects can be used to specify one or several projects to be delivered from the runfolder. Default is to deliver all projects in a runfolder. If the new parameter is used only the specified project/projects will be delivered. If several projects are given as input they should be separated with a comma. Ex, restrict_to_projects=ABC-123,GHI-789
> Specify project to be delivered from runfolder

- actions/workflows/ngi_uu_workflow.yaml
I have not tested these changes, but I have a hard time seeing that it would break anything since the other workflows already do verify the certs nowadays.
> Verify ssl certs on irma api gateway interaction

- scripts/runfolder_search.py
- scripts/trace_runfolder.py
Enables arteria operators to search for runfolders using e.g. flowcell ID. Output contains runfolder state and biotank information. This script can be improved a lot, but this is a start. Props to @johandahlberg who supplied the backbone of the script. 
All actions matching "workflow" will now be listed for a certain trace tag. The reason for this is to include delivery workflows as well as archive workflows that have been started manually. The sync_workflow will also be listed, but personally I think that is OK.
> Runfolder search and modification to trace_runfolder.py

- actions/arteria_delivery_service.py
- actions/delivery_project_workflow.yaml
- actions/delivery_runfolder_workflow.yaml
- actions/delivery_runfolders_for_project_workflow.yaml
- actions/delivery_service_stage_project.yaml
- actions/delivery_service_stage_runfolder.yaml
- actions/delivery_service_stage_runfolders_for_project.yaml
- actions/workflows/delivery_project_workflow.yaml
- actions/workflows/delivery_runfolder_workflow.yaml
- actions/workflows/delivery_runfolders_for_project_workflow.yaml
This brings the delivery workflow up to date with who the `arteria-delivery` service now works, keeping track of previous deliveries. Further more it adds a new workflow to delivery all known runfolders for a project.
This has not yet been fully validated, but informal testing is done, and I think we are ready to merge this.
> New delivery workflows

- config.yaml
- rules/mv_runfolders_from_incoming_to_processing.yaml
- sensors/incoming_sensor.py
- sensors/incoming_sensor.yaml
- sensors/runfolder_sensor.py
This patch adds the ability to configure the user and keyfile to use when doing the remote `mv` action for moving runfolders from 'incoming' to 'runfolders'.
> incoming folder: make user/key for move command configurable

- scripts/runfolder_search.py
Because of new format of runfolder_svc_urls in config.yaml, runfolder_search.py did not work. This PR adapts the script to the new format.
> Adapted script to URLs in config
